version: "3"

volumes:
  postgres-data:

services:
  zwei:
    image: jqs7/zwei
    restart: always
    environment:
      - ZWEI_ADDRESS=postgres
      - ZWEI_USER=jqs7
      - ZWEI_DATABASE=zwei
      - ZWEI_TOKEN=<telegram-bot-token>
  postgres:
    image: postgres
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=
      - POSTGRES_USER=jqs7
      - POSTGRES_DB=zwei
